### ISSUE TITLE
Question: Does this build also support TP-Link 722N for 2nd Wifi Adapter and USB-Stick for Memory?

### ISSUE THREAD

**Issue by careyer** [xchwarze/AR150-WiFiPineapple-2019#1]
Thanks for sharing this build!
Awesome Job!

**Comment by MR5A1NT** [comment]
currently testing it with this setup (v1 TL-WN722N, 16gb flash drive) seem to be working ok

**Comment by xchwarze** [comment]
TP-Link 722N use ath9k driver so it should work
https://wikidevi.com/wiki/TP-LINK_TL-WN722N_v1.x

**Comment by careyer** [comment]
Great! I'll give it a shot then! Thank you very much and sorry for opening an "issue".. it was just meant as a question and for means of discussing things! :-)
