### ISSUE TITLE
Problem with ssh conection and install some modules dependecies

### ISSUE THREAD

**Issue by ukn19** [xchwarze/AR150-WiFiPineapple-2019#10]
Hello. I'm using this firmware gl-ar150-nano-2.6.2-private.bin in my ar150 but I can't connect to ssh and I can't install dependencies to sslplit module. I have flashed the firmware a few times but It doesn't work. Anyone has any idea how can I solve this? Thank you all

**Comment by xchwarze** [comment]
**The only way for debug fw problems is via serial console**
https://wiki.d2air.com/_detail/hardware:router:glinet-serial.jpg?id=hardware%3Arouter%3Agl-ar150

The uploaded versions are tested, although they may have their details as they are not the original hardware.
