### ISSUE TITLE
“Open AP SSID” Unable to connect

### ISSUE THREAD

**Issue by designex** [xchwarze/AR150-WiFiPineapple-2019#11]
hello，2.6.2 Using ar9721usb network card，“Open AP SSID” SSID can be searched, but cannot be connected.

**Comment by xchwarze** [comment]
tested in last version and works ok
this is from forum

>  Its not a bug, in latest Firmware release the default setting of the Client filter is set to "Allow mode" so requires MAC addresses of devices you want to allow access.
> 
> This is a wise move from the manufacturer as this actually puts responsibility back to the user to use the device legally out of the box. And some new users may not have even known what they were doing.
> 
> It can be changed and you can still allow any device to connect... but thats on you, not Hak5.
