### ISSUE TITLE
The WiFi pineapple is still booting infinitely

### ISSUE THREAD

**Issue by ghost** [xchwarze/AR150-WiFiPineapple-2019#12]
I'm stuck in a loop of "The Wifi pineapple is still booting, Please wait until the WiFi Pineapple has fully booted. The setup will continue automatically."

doesn't matter how long i wait, i won't change, can someone help me please? (:

Firmware flashing: gl-ar150-nano-2.7.0.2-private.bin

![image](https://user-images.githubusercontent.com/4770542/77017043-1b0b8600-6958-11ea-8c25-2b80343077fc.png)

**Comment by elliot-holley** [comment]
If you are stuck at the message "The WiFi Pineapple is still booting" don't panic, this is a known issue with running the WiFi Pineapple firmware on the AR150. All you have to do is ssh into the AR150 with the username root and password you set originally when you booted the AR150 right out of the box. Executing the command jffs2reset -y && reboot should resolve your problems.

- the notes

**Comment by ghost** [comment]
> Se você estiver preso na mensagem "O WiFi Pineapple ainda está inicializando" não entre em pânico, esse é um problema conhecido ao executar o firmware WiFi Pineapple no AR150. Tudo o que você precisa fazer é ssh no AR150 com o nome de usuário root e a senha que você definiu originalmente quando inicializou o AR150 imediatamente. A execução do comando jffs2reset -y && reboot deve resolver seus problemas.
> 
> * as notas

ssh: connect to host 172.16.42.1 port 22: Connection refused

Unfortunately I can't connect to ssh, I'll try to write to eprom directly one hour.

**Comment by xchwarze** [comment]
https://github.com/xchwarze/AR150-WiFiPineapple-2019/issues/10#issuecomment-599176343

**Comment by xchwarze** [comment]
reflash with last version
