### ISSUE TITLE
Creating Documentation

### ISSUE THREAD

**Issue by pclever1** [xchwarze/AR150-WiFiPineapple-2019#17]
Hello, I am planning to make a nice guide on how to do this in the coming weeks and I have some questions.
I plan to make a website with screenshots and a good step by step list of instructions linking to this repo.
Before doing that I have some questions:

1. **Is there an existing guide out there?**

2. **Is this the best / most up to date repo for the AR150?**

3. **Are there any notable disadvantages to using an AR150 vs the Hak5 product?**

4. **What is the difference between?**
- gl-ar150-nano-2.7.0.12-normal.bin
- gl-ar150-nano-2.7.0.12-optimized.bin

5. **When are these run?**
- set flash IP.bat
- set pineapple IP.bat

6. **Is the "gpl" folder needed for installation?**

... I also plan to compare it with a Pumpkin Pi (raspberry pi alternative)

Thanks!

**Comment by pclever1** [comment]
Additionally.... Would the GL AR300M work with this firmware? (https://www.amazon.com/dp/B01K6MHRJI)
It looks to be almost the same thing with:

- 2 antennas
- more RAM
- Nand flash
- and more bandwidth.

**Comment by xchwarze** [comment]
Thanks for help pclever1!

1. **Is there an existing guide out there?**
Nope, but in major cases the only step for use this fw is flash it

2. **Is this the best / most up to date repo for the AR150?**
Yes. And it is the most stable.

3. **Are there any notable disadvantages to using an AR150 vs the Hak5 product?**
They would have to be identical. You should try an original NANO to see if there really are any differences. 
There shouldn't be.

4. **What is the difference between?**
- gl-ar150-nano-2.7.0.12-normal.bin (normal openwrt build)
- gl-ar150-nano-2.7.0.12-optimized.bin (build with custom optimizations https://github.com/xchwarze/AR150-WiFiPineapple-2019/tree/master/gpl/patches)

5. **When are these run?**
These are the old scripts to set the ips in windows

6. **Is the "gpl" folder needed for installation?**
From the folder readme:  The intention of this is to help those who want to make a custom compilation.
This can also help make a build for other router versions. (like AR300)

**Comment by pclever1** [comment]
Thanks for answering my questions so quickly!
I received all the parts I ordered and got it up and running just great.... I have a few follow up questions if you don't mind:


1. SSH isn't working for me on the management network. I am able to access the web gui on 172.16.42.1:1471 but "SSH root@172.16.42.1" returns "Connection refused" ... Is there a setting to enable SSH somewhere?

2. Can I connect a 5ghz USB antenna, if so will drivers be installed for only specific models? (eg: [$15 TP-Link AC600 Dual Band](https://www.amazon.com/Wireless-desktop-10-9-10-14-Archer-T2U/dp/B07P5PRK7J))

3. Will the device benefit from having more than 2 antennas?

4. Firmware updates, will the device need to be downgraded first (holding reset for 10 seconds on power up, [source](https://wiki.wifipineapple.com/#!troubleshooting.md)) or can it use the built in updater?

Thanks again!

**Comment by pclever1** [comment]
Hello again,
I've been doing a lot with this project this week and I am having a new issue I was wondering if you could help with.

I am unable to start PineAP (Recon scans fail), when I first flashed it this feature was working but suddenly it stopped. Without SSH access I can only view a few logs and they don't show anything useful about this issue.

The Hak5 forms say to do a firmware recovery in order to fix the problem. 
**Can you tell me how I can safely reflash the device?**

I tried holding the reset button for ~15 seconds while booting, 2 LEDs stayed on and nothing appeared to happen... After about 10min I unplugged it and powered it back on and nothing had changed (wifi pineapple was still installed along with my settings)

**Edit:**
I followed the official guide from GL.iNet (https://www.youtube.com/watch?v=K6t0GSg-TU0) to reflash the device but for some reason I couldn't connect to 192.168.1.1 on either the LAN or WAN ports. Have any of you tried doing this before?


**Edit 2:**
I tried a few more times and found out that there is a very specific amount of time you need to hold the button for to get into flash mode. Too long or too short and it won't work. Once you see 2 green LEDs you can let go and one LED should turn off. If the second LED stays on you need to start over.


Flashing was easy and left most of my settings in place (including SSID names, and login creds), the flash did fix my original issue with the PineAP not starting. 


Thanks!

**Comment by xchwarze** [comment]
Hi! I am finishing some projects and I have little time to respond, sorry!
1. I think it is sometimes failing to assign the ip. so maybe that's why you can't connect
1. I think it should work, but being an exact copy of the nano you will not be able to use the 5ghz with pineap
1. With 2 antennas it works exactly the same as the original hard. I use it like this for +1 year
1. This is the only way for update

**Comment by p4thw4yz** [comment]
solid work xchwarze, Ive been using my Ar150 with 2.7.0-optimized for the last few months a few times a week with no issue, also using 2 added usb wifi adapter on the 2.4 band, haven't been able to get anything 5ghz to work yet. Also been trying to compile a version for AR300M as have one running on 2.0.2 that i found on the net ( haven't done custom openwrt firmware before so work in progress...likes to fail). If we could find a device that uses the same processor as tetra, could implement a 5ghz version? Once i have figured out compiling ill give a few versions a try. Just letting everyone know my interest so can try help out if needed.

**Comment by LinuxOperator** [comment]
Yes I am sure there is interest in a 5Ghz DIY pineapple however I haven't seen any good options. From my understanding GL.iNET doesn't make any products with a 5Ghz radio. 

Also don't quote me on this but I am pretty sure that using the AR150/Nano you can capture some 5Ghz clients... However its not nearly what you get from 2.4Ghz.

**Comment by p4thw4yz** [comment]
Yeah, i have found some 5ghz clients but it is hit an miss, guessing its dependent on individual clients and how there devices are configured. I had limited success with 5ghz adapters showing up on the console side but not through the pineapple gui.

**Comment by brightplastik** [comment]
> 
> 
> If we could find a device that uses the same processor as tetra, could implement a 5ghz version?

Indeed, the AR300M uses exactly that CPU (AR9344)! And having 128Mb of NAND, there should be plenty of space for the image! Therefore, porting the firmware for the Tetra instead of Nano, it should give us 5Ghz spectrum with less than half of the price, and only with a difference on the radio chipsets used. "Kmod-usb-package" and maybe a USB RT3070 might do the trick, perhaps, as there are drivers that enable injection and AP mode on linux for that chipset.
But unfortunately, this is all speculation. I have no knowledge. I don't know how to build and port.

**Comment by IvanBayan** [comment]
I apologize for hijacking an issue, but I hope it's better than creating a new one.
1. What the difference between firmwares with **imagebuilder** suffix and without it?
2. I've flashed optimized version. When I do recon scan with live checkbox I see no result. Only way to see stations/clients is clear checkbox and use time limited scans. Is it expected result or not (I did jffs2reset -y  but it doesn't helped).

Thanks.

**Comment by xchwarze** [comment]
@IvanBayan I think in some point the original method became unstable with the base version change.
Anyway the new method works perfect.

**Comment by IvanBayan** [comment]
A little update, may be it will helpful. Looks like without usb drive and swap partition it became a little unstable. I added a usb drive with swap, it allowed to do recon scans without issues.
BTW, I put rt modules config above atheros, it allows to use PineAP with integrated atheros adapter which seems  better than RT5370 proposed in readme.

**Comment by xchwarze** [comment]
I don't remember if the busibox fdisk was stable in that version of the firmware.
If it doesn't work, you just have to install fdisk from opkg and format a pendrive from the pineapple menu.

These are the notes I made to the prespect in the other repo:
5. Busybox applets list:
```
# openwrt: used 118 applets
ash cat chgrp chmod chown cp date dd df dmesg echo egrep false fgrep fsync grep gunzip gzip kill ln lock login ls mkdir mknod mktemp mount mv netmsg netstat nice passwd pidof ping ping6 ps pwd rm rmdir sed sh sleep sync tar touch traceroute traceroute6 true umount uname vi zcat halt hwclock ifconfig ip mkswap pivot_root poweroff reboot route start-stop-daemon swapoff swapon switch_root sysctl udhcpc awk basename bunzip2 bzcat clear cmp crontab cut dirname du env expr find flock free head hexdump id killall less logger md5sum mkfifo nc nslookup pgrep printf readlink reset seq sha256sum sort strings tail tee test time top tr uniq uptime wc which xargs yes [ [[ brctl chroot crond ntpd 

# nano: used 114 applets
ash bash cat chgrp chmod chown cp date dd df dmesg echo egrep false fgrep fsync grep gunzip gzip kill ln lock login ls mkdir mknod mktemp mount mv netmsg netstat nice passwd pidof ping ping6 pwd rm rmdir sed sh sleep sync tar touch traceroute true umount uname vi fdisk halt hwclock ifconfig ip mkswap pivot_root poweroff reboot route start-stop-daemon swapoff swapon switch_root sysctl udhcpc awk basename clear cmp crontab cut dirname du env expr find flock free head hexdump id killall less logger md5sum mkfifo nslookup pgrep printf readlink reset seq sha256sum sort tail tee test time top tr uniq uptime uuencode wc which xargs yes [ [[ brctl chroot crond ntpd 

# tetra: used 118 applets
ash cat chgrp chmod chown cp date dd df dmesg echo egrep false fgrep fsync grep gunzip gzip kill ln lock login ls mkdir mknod mktemp mount mv netmsg netstat nice passwd pidof ping ping6 pwd rm rmdir sed sh sleep sync tar touch traceroute traceroute6 true umount uname vi zcat fdisk halt hwclock ifconfig ip mkswap pivot_root poweroff reboot route start-stop-daemon swapoff swapon switch_root sysctl udhcpc awk basename bunzip2 bzcat clear cmp crontab cut dirname du env expr find flock free head hexdump id killall less logger md5sum mkfifo nslookup pgrep printf readlink reset seq sha256sum sort strings tail tee test time top tr uniq uptime uuencode wc which xargs yes [ [[ brctl chroot crond ntpd 
```
Diferences with Openwrt Busybox build
```
Nano build
--------------------
Remove: zcat bzcat traceroute6 bunzip2 strings
Add: bash uuencode fdisk

Tetra build
--------------------
Remove: NONE
Add: uuencode fdisk
```
If you don't want to do a custom Busybox build you can install fdisk and mpack.
Don't forget to refactor the uses of uuencode! (reporting script)
