### ISSUE TITLE
Pineapple Invalid Argument

### ISSUE THREAD

**Issue by unkn0wn-wifi** [xchwarze/AR150-WiFiPineapple-2019#18]
hi there, ive encountered an issue where the pineapple doesn't want to do internet sharing on my kali linux box and all it shows as detecting and on rare occations if it detects it says "invalid argument" and just shows the screen to the web gui. please help. and im a beginner Youtuber named 'unkn0wn" and i have tried this before but with a 50% success rate i want to get a 100% success rate and do a video on my channel on this. www.youtube.com/c/blankdot1   . And i want to make this a big project. i want to work with you and dev on some ideas and bring it to life. please contact me via email kingsnakeyt1@gmail.com so i can express further on the ideas i have and what we can do. please can you contact me and help me with this issue :) thanks!
![20200902_220546](https://user-images.githubusercontent.com/70666455/92036775-a80c9500-ed68-11ea-82e9-93ff51dd9751.jpg)

**Comment by xchwarze** [comment]
I think the problem is that the dhcp fails to assign ip.
The failure is random.
Maybe some configuration in dhcp was wrong

**Comment by unkn0wn-wifi** [comment]
Can you do a write up on your github as me and my viewers encounter this
issue and the ethernet and wan ports are switched around.

**Comment by xchwarze** [comment]
It seems that in the latest versions dhcp sometimes fails. 
PR are welcome
