### ISSUE TITLE
AR300M variant

### ISSUE THREAD

**Issue by p4thw4yz** [xchwarze/AR150-WiFiPineapple-2019#19]
Awesome work. Been using the 2.7.0 build you did. I have a AR300M, I found a version of 2.0.2. And I've been trying to compile my own version of 2.7.0 for the AR300M. Been able to extract the files with binwalk but no experience with openwrt firmwares and keep getting met with errors. Any chance of a version compiled for the AR300M. With the 2.0.2 version it just seems abit snappier than on the ar150

**Comment by xchwarze** [comment]
Without the hardware it is something complicated to do.
Anyway in this repo are all the tools published to do something like this.

**Comment by p4thw4yz** [comment]
Yeah I have the hardware, just been having trouble getting the build to complete. Everytime I sort out 1 failure another one happens. All good. I'll keep trying
