### ISSUE TITLE
web GUI / SSH not working ?

### ISSUE THREAD

**Issue by b3rt1ng** [xchwarze/AR150-WiFiPineapple-2019#20]
I just got an GL-AR150 router and flashed the [2.0.7 optimized firmware](https://github.com/xchwarze/AR150-WiFiPineapple-2019/blob/master/gl-ar150-nano-2.7.0.12-optimized.bin) using the original web GUI of the router, on the upgrade firmware section. 
Then, I rebooted the AR150 and it proprely showed up as "Pineapple_94B0", I can also connect myself.
But when i try to see the web GUI, nothing happend.
I tried to connect using the regular IP of the supposed web interface: http://172.16.42.1:1471/
I first thought that the IP address had not been set correctly so i tried to use the router ip wich were: http://169.254.121.246/
but nothing as well.
Is it a common issue, or maybe i did something wrong ?

**Comment by xchwarze** [comment]
It seems that in the latest versions dhcp sometimes fails.
This does not happen in other versions
