### ISSUE TITLE
No initial setup

### ISSUE THREAD

**Issue by ghost** [xchwarze/AR150-WiFiPineapple-2019#21]
After flashing firmware I accessed the initial web GUI page and appears the login form even without making the initial setup. Is there a default password or is there a way to force the initial setup?
Regards

**Comment by xchwarze** [comment]
you may need to format the overlayFS

**Comment by ghost** [comment]
it could be a solution but I cannot login by ssh too.

**Comment by xchwarze** [comment]
first reinstall gl-inet original flash, then format overlayFS

**Comment by ghost** [comment]
Problem resolved. Thanks for the fast reply.

**Comment by ghost** [comment]
Keep the good work.
