### ISSUE TITLE
More than willing to acknowledge your credit.

### ISSUE THREAD

**Issue by brightplastik** [xchwarze/AR150-WiFiPineapple-2019#22]
Hello, sorry for opening an issue, but I hope this will make us communicate.

Since months I'm looking for a way to build an up to date firmware for the GL-AR300M.
A you stated, the last known version of pineapple fw is 2.4.2, and I can't even say if it works or not.
Your repo here looks very promising!
Could you teach me how to port the latest version of pineapple firmware to the AR300M?

I think you're my only chance. The community is quite chaotic about these ports. Yours looks like the most systematic I encountered, but I have a different model to work with.

I congratulate for your excellent up to date work, and hope to learn how to replicate this excellence on another model.

**Comment by brightplastik** [comment]
Hey, I thought about it...and you know what?
Who cares about the credits! I will pay, the equivalence of a new AR300M, if you teach me how to implement the same you did with the AR150. I paid mine 37,10€ on aliex...well, you know where. I can obviously prove it.

It is fair to pay for knowledge. More than for services. I'm not rich (otherwise I would buy the actual product with closed eyes!) but considering that the price of two boxes (mine and the value given to you) is still lower than the actual pineapple, it is good for me.
The value of learning to do something very useful out of simple tools in invaluable, in my opinion. So I'd be very happy if you accepted my offer.
Let me know if you're willing to do this with me!

My sincere congratulations,
Gabriel

P.S: I'm not stupid, and I have several tools including uart, but not very accustomed with the guts of linux and compiling. I only scratch the surface, but on a regular basis. I couldn't figure out what to do with the files in picture, for example. They are needed for compiling an old version (2.4.2 as you correctly pointed out) by @bugsysundayTHOT, but I couldn't make it. Unfortunately I need a guide, being an apprentice. It seems to me I need to learn how to build a buildroot, and have no clue of what an SDK and imagebuilder are, or how to include patches and kernels.

![pineap242files](https://user-images.githubusercontent.com/45295288/98391992-abb5e400-2057-11eb-90de-c703c176f4b2.jpg)

**Comment by xchwarze** [comment]
In my fucking country it became quite expensive to bring hardware even from China...

I'll tell you how anyway.
1. Use this config https://github.com/xchwarze/AR150-WiFiPineapple-2019/blob/master/gpl/config and change the target
2. With FMK extract from my fw the panel, the crack and the configuration files, boot and first start
3. Bring it all together in a new fw with FMK

Surely you have to use WinMerge or some similar tool.
The build is done with OpenWrt 19.07.2.

Keep in mind that making a port takes a lot of time and a lot of work.
And it really can be quite frustrating.

**Comment by brightplastik** [comment]
Firmware-mod-kit by brianpow. 

Got it.
Honestly, I spent a considerable amount of time on duckduckgo only to understand this little detail. 
Gosh, I'm such a noob.
Despite that, I'm super excited to face this method, as it already seems a shortcut, related to a whole build process.

Question: do I still need to make a 19.07.2 openwrt image with "make" and buildroot? 

...still trying to interpret your indications, maybe. I'll have some attempts at it. 

I'll keep you informed, if it doesn't annoy you.

And about shopping merch from your Country...well...you totally deserve an AR300M to tinker with. I would be proud to send you one, flashed by me with a 2.7.0 pineapple fw, once I manage to make it.

My name is Gabriel, and I'm glad to know you. My pleasure.

May you have a gorgeous life, xchwarze!

**Comment by brightplastik** [comment]
@xchwarze, just for a confrontation:

FMK:
extract-firmware.sh yourfw
Error: no supported file system found!

Old-extract.sh yourfw
Error: filesystem not extracted properly.

Tried many forks of the original FMK, as it seems outdated. Now on the kali fork, but 
none is suiting what you mentioned.

Any ideazzzz? 🤦‍♂️

EDIT: found this tip 
"some people have had issues running firmware-mod-kit on their favorite distro, personally I have had no issues with Linux Mint 17.3 Cinnamon (64bit) from http://www.osboxes.org/linux-mint/" 

Will try that and report.

Regards,
Suchanoob

**Comment by xchwarze** [comment]
mmm try that:

```
git clone https://github.com/rampageX/firmware-mod-kit fmk-tool
sudo apt-get install git build-essential zlib1g-dev liblzma-dev python-magic bsdmainutils
```

and use like this:

```
fmk-tool/extract-firmware.sh nanofw.bin
```

**Comment by brightplastik** [comment]
New episode of "Suchanoob on the conquer of None".

I succeded installing and using FMK, but it refuses to extract both your normal and optimized .bin
FMK is partly based on binwalk. So I installed and launched binwalk to exclude a malfunction of the one included in FMK.
Binwalk as problems recognizing the filesystem of your images. The same happens to the GL.inet images, but not with a normal openwrt image.
So by now, the only image I was able to extract is a trivial 19.07.4 openwrt.

Maybe this is caused by ubi? What is ubi?
Really dunno what is going on. Please master, teach me.
I attach a log of terminal:
osboxes fmk-tool # ./extract-firmware.sh '/home/osboxes/Desktop/gl-ar150-nano-2.7.0.12-optimized.bin' ar150
Firmware Mod Kit (extract) 0.99, (c)2011-2013 Craig Heffner, Jeremy Collake

Scanning firmware...

Scan Time:     2020-11-16 01:30:39
Target File:   /home/osboxes/Desktop/gl-ar150-nano-2.7.0.12-optimized.bin
MD5 Checksum:  4c0231e3eed974c6bfe155083f59e555
Signatures:    344

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
22            0x16            HTML document header
18213         0x4725          Unix path: /github.com/xchwarze/AR150-WiFiPineapple-2019/commits/master.atom" rel="alternate" title="Recent Commits to AR150-WiFiPineapple-
19298         0x4B62          Unix path: /github.com/xchwarze/AR150-WiFiPineapple-2019/blob/master/gl-ar150-nano-2.7.0.12-optimized.bin" data-pjax-transient>
19466         0x4C0A          Unix path: /api.github.com/_private/browser/stats">
19558         0x4C66          Unix path: /api.github.com/_private/browser/errors">
19669         0x4CD5          Unix path: /api.github.com/_private/browser/optimizely_client/errors">
22611         0x5853          Unix path: /github.com/xchwarze/AR150-WiFiPineapple-2019/blob/master/gl-ar150-nano-2.7.0.12-optimized.bin&quot;,&quot;user_id&quot;:null}}"
48242         0xBC72          Unix path: /github.com/xchwarze/AR150-WiFiPineapple-2019/blob/master/gl-ar150-nano-2.7.0.12-optimized.bin&quot;,&quot;user_id&quot;:null}}"
49179         0xC01B          Unix path: /github.com/xchwarze/AR150-WiFiPineapple-2019/blob/master/gl-ar150-nano-2.7.0.12-optimized.bin&quot;,&quot;user_id&quot;:null}}"
50516         0xC554          Unix path: /github.com/notifications/beta/shelf"></include-fragment>
52761         0xCE19          Unix path: /github.com/xchwarze/AR150-WiFiPineapple-2019/blob/master/gl-ar150-nano-2.7.0.12-optimized.bin&quot;,&quot;user_id&quot;:null}}"
54429         0xD49D          Unix path: /github.com/xchwarze/AR150-WiFiPineapple-2019/blob/master/gl-ar150-nano-2.7.0.12-optimized.bin&quot;,&quot;user_id&quot;:null}}"
55968         0xDAA0          Unix path: /github.com/xchwarze/AR150-WiFiPineapple-2019/blob/master/gl-ar150-nano-2.7.0.12-optimized.bin&quot;,&quot;user_id&quot;:null}}"
56790         0xDDD6          Unix path: /xchwarze/AR150-WiFiPineapple-2019/network/members" class="social-count"
63783         0xF927          Unix path: /xchwarze/AR150-WiFiPineapple-2019/security/overall-count" accept="text/fragment+html"></include-fragment>
68126         0x10A1E         Unix path: /xchwarze/AR150-WiFiPineapple-2019/blob/a3dd0404e3bca795857c6fb4e861348337166cc8/gl-ar150-nano-2.7.0.12-optimized.bin">Permalink
69611         0x10FEB         Unix path: /github.com/xchwarze/AR150-WiFiPineapple-2019/blob/master/gl-ar150-nano-2.7.0.12-optimized.bin&quot;,&quot;user_id&quot;:null}}"
70915         0x11503         Unix path: /github.com/xchwarze/AR150-WiFiPineapple-2019/blob/master/gl-ar150-nano-2.7.0.12-optimized.bin&quot;,&quot;user_id&quot;:null}}"
72286         0x11A5E         Unix path: /github.githubassets.com/images/modules/site/home/astro-mona-alpha.jpg"></image>
72527         0x11B4F         Unix path: /github.githubassets.com/images/modules/site/home/astro-mona.jpg"></image>
73745         0x12011         Unix path: /xchwarze/AR150-WiFiPineapple-2019/refs/master/gl-ar150-nano-2.7.0.12-optimized.bin?source_action=show&amp;source_controller=blo
75616         0x12760         Unix path: /xchwarze/AR150-WiFiPineapple-2019/find/master"
76619         0x12B4B         Unix path: /github.com/xchwarze/AR150-WiFiPineapple-2019/blob/master/gl-ar150-nano-2.7.0.12-optimized.bin&quot;,&quot;user_id&quot;:null}}"
78029         0x130CD         Unix path: /xchwarze/AR150-WiFiPineapple-2019/contributors/master/gl-ar150-nano-2.7.0.12-optimized.bin" class="commit-loader">
79125         0x13515         Unix path: /xchwarze/AR150-WiFiPineapple-2019/raw/master/gl-ar150-nano-2.7.0.12-optimized.bin" id="raw-url" role="button" class="btn btn-sm
80302         0x139AE         Unix path: /xchwarze/AR150-WiFiPineapple-2019/delete/master/gl-ar150-nano-2.7.0.12-optimized.bin" accept-charset="UTF-8" method="post"><inp
81532         0x13E7C         Unix path: /xchwarze/AR150-WiFiPineapple-2019/blob/master/gl-ar150-nano-2.7.0.12-optimized.bin?raw=true">View raw</a>
91057         0x163B1         Unix path: /docs.github.com/en/github/site-policy/github-subprocessors-and-cookies">Learn more</a>
91761         0x16671         Unix path: /docs.github.com/en/github/site-policy/github-subprocessors-and-cookies">Learn more</a>
92520         0x16968         HTML document footer

Extracting 0 bytes of  header image at offset 0
ERROR: No supported file system found! Aborting...

(facepalm)

P.S: if you feel like you what to keep teaching and helping me, is there a place to talk about these matters? Dunno, like a forum, or even a personal email? You can find me as "beplastik", on the gmail address.

**Comment by brightplastik** [comment]
But still, I think all problems are related to a very, very long list of "ftruncate" errors during the preliminary make of FMK. This bloody python is always making huge problems to  me. I run (with positive result) "deps.sh" in src/binwalk, but nonetheless I have a lot of errors during make. Hundreds of errors like this one:

mksquashfs.c: In function ‘write_file_blocks’:
mksquashfs.c:2449:12: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
   ftruncate(fd, bytes);

**Comment by xchwarze** [comment]
maybe you dont have installed squashfs
try this:
https://www.howtoinstall.me/ubuntu/18-04/squashfs-tools/

what OS are you using?
i use ubuntu 18 in a VM

**Comment by brightplastik** [comment]
Illustrius xchwarze, thanks for answering.

Squashfs is correctly installed. `/home/osboxes/fmk-tool/src/binwalk-2.1.1/deps.sh` is taking care of this and all other needed packages.
My VM is now Linux Mint 17.3 Cinnamon x64, as suggested by Patrick Sapinski [here](http://sapinski.com/2016/02/13/wifi-pineapple-firmware-for-gl-inet-gl-ar150/).
I tried as well to build a correct environment in OSX, using [this git](https://github.com/cinquemb/firmware-mod-kit-osx) since I have a hackintosh, but same errors occurred during `make all`
Do you have a working FMK folder? Can you help me replicate your environment? 

I know this is getting ridiculous...but I'm willing to learn. Yet, the learning curve is quite steep. I won't fall in frustration though. I know there's a lot to do, and I'm only getting the needed tools to begin.
I'm on my third VM, and counting...

**Comment by brightplastik** [comment]
Dear @xchwarze,
after many, many noob attempts, I now have a working FMK, on 18.04 VM.

I finally extracted all files from your _optimized_ fw.
![Screenshot from 2020-11-26 17-48-25](https://user-images.githubusercontent.com/45295288/100376935-a7eeff00-3010-11eb-98ce-3e3d9c442713.png)
![Screenshot from 2020-11-26 17-48-42](https://user-images.githubusercontent.com/45295288/100376938-a9202c00-3010-11eb-9afe-b4d447d6c70f.png)
![Screenshot from 2020-11-26 17-48-55](https://user-images.githubusercontent.com/45295288/100376939-a9202c00-3010-11eb-8eb6-ddb3456e7003.png)

Do you think the optimizations will apply on the AR300M as well?



But mainly, now that I have extracted all files, what do I select precisely?

>     2\. With FMK extract from my fw the panel, the crack and the configuration files, boot and first start

Could you explain me this step?




> Keep in mind that making a port takes a lot of time and a lot of work.
> And it really can be quite frustrating.

I do! And I can't say how much admiration I have toward people like you. It's a sort of modern craftmanship. It takes a very long time, and most of time people don't value it correctly.
I know how long you must have spent in front of the pc, and the huge difference between me and you is that you sit in front of the pc doing smart things, while I spent days only to make FMK work without errors. The last 10 days have passed trying to understand why FMK wouldn't extract. See how smart I am? 
Therefore, I hope you can help me, because the difference in knowledge is enormous.

So, take care of yourself, and take my compliments!

Hope to hear from you soon,
Gabriel

P.S: do you have a profile on openwrt forum?

**Comment by brightplastik** [comment]
> 2. With FMK extract from my fw the panel, the crack and the configuration files, boot al in a new fw with FMK
> 

Dear xchwarze, as I mentioned earlier I extracted all needed from your firmware...could you please detail a little more what are the bits I have to merge? 

I have all ready and working. I only need a little tip on what to merge together. 

It would be very very useful to me and all people trying to do the same port of your excellent work! 

Happy Christmas, as possible in these days!

**Comment by brightplastik** [comment]
Hello!

A tiny 2021 advice, so that I can begin this year with an unusual sense of satisfaction? 😂😂😂

**Comment by xchwarze** [comment]
Hello! Basically you have to merge your build with the rootfs folder of fmk.
Your build has the support for the new board and that has to be added to the rootfs.
For this use WinMerge in windows or Meld in Ubuntu

**Comment by 4dvn** [comment]
> Hello! Basically you have to merge your build with the rootfs folder of fmk.
> Your build has the support for the new board and that has to be added to the rootfs.
> For this use WinMerge in windows or Meld in Ubuntu

I know how to patch the pineapd on newest version!

**Comment by TeslaXT** [comment]
> I know how to patch the pineapd on newest version!

Are you saying you have this ported across to the ar300M?

**Comment by TeslaXT** [comment]
> A tiny 2021 advice, so that I can begin this year with an unusual sense of satisfaction?

If you manage to port this could you please share your work on here also? I, Like you, have been looking for this for months however I am not inclined to the same degree of "programming" as you.

**Comment by brightplastik** [comment]
Hello Tesla, I will surely share the endeavours. As you can clearly see from the previous posts, this is all hugely thanks to xchwarze's help. If I manage running a working and recent PineAP I won't miss to alert you all.
I'm not clever. Only stubborn. But I'll probably need some time, meanwhile. 😅

**Comment by 4dvn** [comment]
> > I know how to patch the pineapd on newest version!
> 
> Are you saying you have this ported across to the ar300M?

yes

**Comment by brightplastik** [comment]
> 
> 
> > Hello! Basically you have to merge your build with the rootfs folder of fmk.
> > Your build has the support for the new board and that has to be added to the rootfs.
> > For this use WinMerge in windows or Meld in Ubuntu
> 
> I know how to patch the pineapd on newest version!

That would be useful too, 4dvn!
i sent you an email on hanv@dzus.edu.vn, hope to hear from you.

**Comment by brightplastik** [comment]
Hello @4dvn, I'm here asking for anyone's help. 
Yesterday I even received an email from a github member...he asked me to explain him how to flash @xchwarze 's FW on his ar150. Well, the little I know I share. I told him how.
But regarding the ar300m fork I'm in deadspot. Dunno what to merge, and why. Simply not a connoisseur of firmware builds.

@xchwarze , I am quite embarassed. You are very generous telling me what to do, but I lack the fundamental knowledge, and I might brick the box, merging and damaging the rootfs folder with inappropriate files from the owrt fw. I understand, but only in theory. In practice I should know precisely what I'm doing, but I don't. The rootfs folders are very similar, but what precisely gives support for the AR300M? I just don't know. There are a lot of subfolders in rootfs, and I can't target what to merge.

@4dvn, do you have a firmware for AR300M? Could you share it with us please? I made a fork of your fork, and invited you to collaborate in it. If you can help, having time and knowledge, I would be very grateful. 
I made the fork of the fork only because your fork hasn't got issues section enabled. So we can talk, as here on xchwarze's. Maybe xchwarze is fed up with these requests.

**Comment by xchwarze** [comment]
for build a custom firmware use this toolset https://github.com/xchwarze/wifi-pineapple-cloner

**Comment by xchwarze** [comment]
@brightplastik I think the gl-ar750s is the correct hardware for what you wanted to do. Even quite superior to the original.
I haven't tried it yet but I'm pretty sure about it xD.

**Comment by brightplastik** [comment]
I totally agree with you.
Nonetheless, I'm still in the noob area. 
I tried some months ago to build an image for the AR300M, and failed. Had to recover using UART.
At the moment I own one AR150 and one AR300M. I could sell them on marketplace with PineAP installed and buy the AR750S, but apparently I'm unable to use owrt build environment. 
*facepalm*
