### ISSUE TITLE
PineAP cant enabled

### ISSUE THREAD

**Issue by aoxo2022** [xchwarze/AR150-WiFiPineapple-2019#26]
Sorry for my english

- i download your 2.7.0.xx new bin file for AR150
- i flash it to mw GL AR150 150M (AR150 without antena)
- when i start Recon, PineAP cant start
- then i going to PineAP menu, i cant switch PineAP to enabled

Can you help me?

**Comment by xchwarze** [comment]
Add a external usb wifi for use wlan1mon

**Comment by aoxo2022** [comment]
I do
I use tplink wn722n v1
Still cant switch enabled

I use your gl-ar150-nano-2.7.0.23-imagebuilder-mini.bin

**Comment by xchwarze** [comment]
debug it as if it were a common linux (lsusb, logs, etc)
for example the TL-WN7200ND needs a powered usb hub to work

**Comment by aoxo2022** [comment]
I try use usb hub
Still cant enabled

Then i try your 2.7.0.13 optimized bin
I reflash ar150
And it can enabled
It confused me

Thankyou for answer my question

**Comment by xchwarze** [comment]
The information you are giving is not useful for debugging...
Could you generate a Debug file and attach to a reply in this thread?  You can generate the file by going to Help module, and clicking "Generate Debug File". 
However to use high power adapters they have to be used with powered hubs. If you use a normal hub it won't work because it doesn't have enough amps to power the adapter .

**Comment by aoxo2022** [comment]
Ok. Wait
I reflash with 2.7.0.23

**Comment by aoxo2022** [comment]
[debug.log](https://github.com/xchwarze/AR150-WiFiPineapple-2019/files/8194545/debug.log)
this debug file

![1646624207316666994455484999864](https://user-images.githubusercontent.com/101029515/156963393-c7f43d20-a859-4f57-a6b9-46e286f7f7a4.jpg)

**Comment by aoxo2022** [comment]
I try again
-Flash with 2.7.0.23 mini
-usb adapter alfa awus036h

![16466275097412244111084423563204](https://user-images.githubusercontent.com/101029515/156968242-e1dbc70c-36f6-40ee-a0f5-0fc1f04d841a.jpg)
![16466275569421586693998647231579](https://user-images.githubusercontent.com/101029515/156968279-c8715865-e618-4aba-9a45-52e7ddb80578.jpg)

PineAP Daemon Enabled

this debug fil
[debug (3).log](https://github.com/xchwarze/AR150-WiFiPineapple-2019/files/8194838/debug.3.log)
e

**Comment by xchwarze** [comment]
seems to be a missing driver (tplink)
try this
```
opkg update
opkg install kmod-ath9k-htc
reboot
```

since I don't have that adapter (and that version of hard) I don't know if it works in openwrt, but I suppose that with that driver it would work

**Comment by aoxo2022** [comment]
> 

Ok. Let me try it.

**Comment by aoxo2022** [comment]
Thankyou sir. It works

> seems to be a missing driver (tplink) try this
> 
> ```
> opkg update
> opkg install kmod-ath9k-htc
> reboot
> ```
> 
> since I don't have that adapter (and that version of hard) I don't know if it works in openwrt, but I suppose that with that driver it would work

Tq sir. It works.

My new question. Can i use 2 usb antenna external (with usb powered hub?

**Comment by xchwarze** [comment]
yes, I use 2 usb wlan + 1 pendrive

**Comment by aoxo2022** [comment]
> yes, I use 2 usb wlan + 1 pendrive

Can you tell me your usb powered  hub?
