### ISSUE TITLE
ssh connection is blocked?

### ISSUE THREAD

**Issue by lipomos** [xchwarze/AR150-WiFiPineapple-2019#5]
I can't connect 172.16.42.1 port 22..
Did you block it?

**Comment by meunlo** [comment]
ssh root@172.16.42.1 works for me. What's your error?

**Comment by xchwarze** [comment]
Try reflashing the device.
Maybe your ar150 need a format the jffs2 partition

**Comment by lipomos** [comment]
Alternately flashes GLinet firmware and pineapple firmware several times, GLinet firmware is ssh connected but ssh connection is not possible when pineapple firmware is running

**Comment by lipomos** [comment]
My ar150 is confused I wanted to use 6416a instead, but I tried using the your firmware as described here. https://oct8l.gitlab.io/posts/2019/54/making-a-knockoff-wifi-pineapple-from-a-gl-inet-ar150m/ 6416 wifi pineapple and ssh works! But I can't find wan1mon. In lsusb all devices work fine .. What can i do ..?

**Comment by xchwarze** [comment]
1) flash fw
2) connect to lan port
3) open http://172.16.42.1:1471 and complete the setup
4) connect to ssh

this steps work in my setup
