### ISSUE TITLE
PineApd did not work.

### ISSUE THREAD

**Issue by ReVCodeX** [xchwarze/AR150-WiFiPineapple-2019#6]
First of all thx for your great work. I guess i have done somthing wrong. Maybe wrong setting. Flashing over Uboot with no problem. I have a RTL8192CU usb wifi for second wifi. It is visible as wmon1. Till now i did not use Usb for second storage. I have tryed all of your builts with same problem. When i try to start Recon the Pineapd shows a bargraph running. But when its finished it shows that there are no logs, and that i should run Recon first. Somtimes when i try to give Recon a second try Pineapd didn,t start. When i try to aktivate Pineapd over menue "Pineap" most times it did not change its status. Sometimes it changes from off to on, but just for a few seconds. What have i done wrong?

**Comment by xchwarze** [comment]
Hello!
For what I have been reading in the official forum that error is also in the original nano.
I would really need an original nano to know if there is an error in my build.
Anyway, everything would indicate that this defect is also in the original.
