### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by meunlo** [xchwarze/AR150-WiFiPineapple-2019#7]
This is not an issue. First, thank you for maintaining this and keeping us all up-to-date. I have tried to follow a few other guides online to build my own. However quite a few of the links available are out of date, or point to  gits/ firmware builders that are no longer maintained. I am interested in trying this project on a gl-inet AR750
GL-AR750
Powered by Qualcomm QCA9531 SoC,650MHz CPU
300Mbps(2.4G) + 433Mbps(5G) high speed
DDR2 128MB RAM
Support external storage up to 128GB
16MB Nor flash
Small, light, easy to use
OpenWrt/LEDE pre-installed

This Same CPU was used in the GL-AR300, which has already proven to run the PineAP firmware.

I have followed instructions for extracting the firmware for the Tetra 2.6.2 using binwalk, However, I'm not sure if cloning the current openwrt 19.07 git and continuing with the instructions I've found is the best step or not, the instructions i'm following are dated, and suggest cloning https://github.com/domino-team/openwrt-cc, which is openwrt 15.05. this doesn't seem to be a step in the right direction. Any help you can provide would be greatly appreciated, It could be pretty cool to have a low cost Tetra for development as well 👍

**Comment by xchwarze** [comment]
Hi meunlo! 
Try this:
1) Clone https://github.com/openwrt/openwrt/tree/openwrt-19.07 and build
2) Use https://github.com/rampageX/firmware-mod-kit for...
  A) Extract tetra FS
  B) Clean modules folder and paste with your build modules content
  C) Use this repo pineap and pineapd cracks
  D) Create new FW

**Comment by meunlo** [comment]
Thank you for your reply, my first hurdle will be obtaining a more suitable build environment as my WSL instance failed pre-req check for not being a case-sensitive file system.

**Comment by xchwarze** [comment]
Try Ubuntu LTS in vmware or virtual box
