### ISSUE TITLE
fowarding internet through ar150 pineapple problem

### ISSUE THREAD

**Issue by coolguybw** [xchwarze/AR150-WiFiPineapple-2019#9]
i cant seem to find out how to share internet to the pineapple even if i use the scripts found here: https://khasmek.github.io/howto/2016/09/27/ar150-pineapple-install 

can anyone help me?

**Comment by mankidavu** [comment]
You can use the client mode in "networking " settings area.

**Comment by xchwarze** [comment]
maybe fix in last version
